import type { Story, WorkItemsDocument } from "./types.js";

const SEED_TIMESTAMP = "2026-07-18T00:00:00.000Z";

const seedStories: Story[] = [
  {
    id: "S0.1",
    epicId: "track-0",
    epicTitle: "Attachments & Ingress",
    title: "Vision + text-document delivery",
    intent:
      "Deliver image attachments to the model as data URLs and text attachments as decoded text so the agent can use both.",
    acceptanceCriteria: [
      "Images reach the model inline as data URLs for vision, and text files reach it as decoded text parts.",
      "Delivery is verified; text-file inline UX is superseded by Track 6 while images remain inline.",
    ],
    status: "shipped",
    routing: "pi:luna",
    reviewGate: "none",
    deps: [],
    authoredBy: "David",
    createdAt: SEED_TIMESTAMP,
    updatedAt: SEED_TIMESTAMP,
  },
  {
    id: "S0.2",
    epicId: "track-0",
    epicTitle: "Attachments & Ingress",
    title: "Ingress Cores showcase",
    intent:
      "Showcase Sheets round-trip and .env paste-to-populate behavior by composing the existing clipboard, delimited, and dotenv primitives.",
    acceptanceCriteria: [
      "TypeScript typechecks with 0 errors and the Vite build passes.",
      "The two exhibits render and round-trip correctly in the browser.",
    ],
    status: "shipped",
    routing: "claude:sonnet",
    reviewGate: "browser:David",
    deps: [],
    authoredBy: "David",
    createdAt: SEED_TIMESTAMP,
    updatedAt: SEED_TIMESTAMP,
  },
  {
    id: "S0.3",
    epicId: "track-0",
    epicTitle: "Attachments & Ingress",
    title: "Land the milestone as commits",
    intent:
      "Land the attachment milestone in concern-grouped commits without pushing, while leaving graduated main and unrelated work in place.",
    acceptanceCriteria: [
      "Create separate concern-grouped commits with trailers, leave graduated main and unrelated WIP untouched, and report the hashes.",
    ],
    status: "ready",
    routing: "self",
    reviewGate: "peer",
    deps: ["S0.1", "S0.2"],
    authoredBy: "David",
    createdAt: SEED_TIMESTAMP,
    updatedAt: SEED_TIMESTAMP,
  },
  {
    id: "S0.4",
    epicId: "track-0",
    epicTitle: "Attachments & Ingress",
    title: "Durable attachment reload",
    intent:
      "Separate attachment display state from model input so thumbnails survive refresh without inline bloat or SSRF-blocked URL references.",
    acceptanceCriteria: [
      "Specify a display-versus-model split that preserves attachment thumbnails across refresh without sending text files inline or relying on blocked local URLs.",
    ],
    status: "spec",
    routing: "self",
    reviewGate: "none",
    deps: ["S0.1"],
    authoredBy: "David",
    createdAt: SEED_TIMESTAMP,
    updatedAt: SEED_TIMESTAMP,
  },
  {
    id: "S1.0",
    epicId: "track-1",
    epicTitle: "Roadmap & review surface",
    title: "Shape decision",
    intent:
      "Choose a dedicated Roadmap workspace with live agent-editable stories and a David review queue rather than a lighter read-only render.",
    acceptanceCriteria: [
      "David decides between the dedicated Roadmap workspace and the lighter read-only render, recording the choice before Track 1 implementation proceeds.",
    ],
    status: "spec",
    routing: "self",
    reviewGate: "decision:David",
    deps: [],
    authoredBy: "David",
    createdAt: SEED_TIMESTAMP,
    updatedAt: SEED_TIMESTAMP,
  },
  {
    id: "S1.1",
    epicId: "track-1",
    epicTitle: "Roadmap & review surface",
    title: "work-items-store package + story schema",
    intent:
      "Provide a durable work-items store for the roadmap stories, review assignments, comments, and append-only revisions.",
    acceptanceCriteria: [
      "The @workspace/work-items-store package mirrors review-store, defines the Story schema, persists append-only revisions, and seeds this story list.",
    ],
    status: "ready",
    routing: "pi:luna",
    reviewGate: "peer",
    deps: ["S1.0"],
    authoredBy: "David",
    createdAt: SEED_TIMESTAMP,
    updatedAt: SEED_TIMESTAMP,
  },
  {
    id: "S1.2",
    epicId: "track-1",
    epicTitle: "Roadmap & review surface",
    title: "sigil-story-* Gonk tools",
    intent:
      "Expose story upsert, transition, and review-assignment mutations through Gonk so chat actions update the roadmap board.",
    acceptanceCriteria: [
      "tools/list shows the three sigil-story tools, driving one in chat mutates the board, each returns a clientCommand, and the exec tier remains denied by policy.",
    ],
    status: "ready",
    routing: "pi:luna",
    reviewGate: "peer",
    deps: ["S1.0", "S1.1"],
    authoredBy: "David",
    createdAt: SEED_TIMESTAMP,
    updatedAt: SEED_TIMESTAMP,
  },
  {
    id: "S1.3",
    epicId: "track-1",
    epicTitle: "Roadmap & review surface",
    title: "Roadmap workspace UI",
    intent:
      "Render the seeded stories as a status board with story editing and a David review queue that feeds decisions back through the domain-outcome loop.",
    acceptanceCriteria: [
      "The workspace renders the seeded stories, approving a review item transitions it, the route header comment is present, typecheck and build pass, and the browser console is clean.",
    ],
    status: "ready",
    routing: "claude:opus",
    reviewGate: "browser:David",
    deps: ["S1.0", "S1.1"],
    authoredBy: "David",
    createdAt: SEED_TIMESTAMP,
    updatedAt: SEED_TIMESTAMP,
  },
  {
    id: "S1.4",
    epicId: "track-1",
    epicTitle: "Roadmap & review surface",
    title: "Agent authoring loop",
    intent:
      "Make story proposals, updates, and David review assignments a normal part of the agent's working loop.",
    acceptanceCriteria: [
      "Agent instructions and a skill cause the agent to propose or update stories and assign David reviews as a normal part of work, closing the in-tool review loop.",
    ],
    status: "spec",
    routing: "self",
    reviewGate: "browser:David",
    deps: ["S1.2", "S1.3"],
    authoredBy: "David",
    createdAt: SEED_TIMESTAMP,
    updatedAt: SEED_TIMESTAMP,
  },
  {
    id: "S2.0",
    epicId: "track-2",
    epicTitle: "Agent operations surfaces",
    title: "Resource-manager shell spec",
    intent:
      "Specify one composable list-plus-detail resource-manager shell for the agent, skill, and tool-permission consoles.",
    acceptanceCriteria: [
      "Produce the short shared list-and-detail pattern specification that S2.1 through S2.3 can reuse.",
    ],
    status: "spec",
    routing: "self",
    reviewGate: "none",
    deps: [],
    authoredBy: "David",
    createdAt: SEED_TIMESTAMP,
    updatedAt: SEED_TIMESTAMP,
  },
  {
    id: "S2.1",
    epicId: "track-2",
    epicTitle: "Agent operations surfaces",
    title: "Manage agents",
    intent:
      "Provide a resource-manager surface to add, edit, and view defineAgent configuration including model, instructions, connections, and subagents.",
    acceptanceCriteria: [
      "The manage-agents surface supports adding, editing, and viewing defineAgent model, instructions, connections, and subagents over the shared shell.",
    ],
    status: "spec",
    routing: "claude:sonnet",
    reviewGate: "none",
    deps: ["S2.0"],
    authoredBy: "David",
    createdAt: SEED_TIMESTAMP,
    updatedAt: SEED_TIMESTAMP,
  },
  {
    id: "S2.2",
    epicId: "track-2",
    epicTitle: "Agent operations surfaces",
    title: "Manage skills",
    intent:
      "Provide a resource-manager catalog and authoring surface over the Gonk Core skills lifecycle.",
    acceptanceCriteria: [
      "The manage-skills surface catalogs and authors skills through the Gonk Core @gonk/skills lifecycle over the shared shell.",
    ],
    status: "spec",
    routing: "claude:sonnet",
    reviewGate: "none",
    deps: ["S2.0"],
    authoredBy: "David",
    createdAt: SEED_TIMESTAMP,
    updatedAt: SEED_TIMESTAMP,
  },
  {
    id: "S2.3",
    epicId: "track-2",
    epicTitle: "Agent operations surfaces",
    title: "Tool permissions & catalog",
    intent:
      "Provide a catalog and editor for tools and their per-tool approval defaults over the existing approval provider boundary.",
    acceptanceCriteria: [
      "The tool-permissions surface views tools and sets per-tool approval defaults over agent-tool-approval.ts and the Gonk registry ApprovalProvider.",
    ],
    status: "spec",
    routing: "claude:sonnet",
    reviewGate: "none",
    deps: ["S2.0"],
    authoredBy: "David",
    createdAt: SEED_TIMESTAMP,
    updatedAt: SEED_TIMESTAMP,
  },
  {
    id: "S3.1",
    epicId: "track-3",
    epicTitle: "Agent memory & workspace",
    title: "Memory",
    intent:
      "Choose a substrate and contract for durable agent memory, including what is remembered, who writes it, and how it is surfaced.",
    acceptanceCriteria: [
      "Specify durable store, recall, and edit behavior, decide between Mirk and Eve sandbox substrate, and define the retrieval contract before dispatch.",
    ],
    status: "spec",
    routing: "self",
    reviewGate: "none",
    deps: [],
    authoredBy: "David",
    createdAt: SEED_TIMESTAMP,
    updatedAt: SEED_TIMESTAMP,
  },
  {
    id: "S3.2",
    epicId: "track-3",
    epicTitle: "Agent memory & workspace",
    title: "Persistent blackboard",
    intent:
      "Define a durable cross-turn and cross-session scratch space distinct from the transcript and project it into context.",
    acceptanceCriteria: [
      "Specify a persistent blackboard distinct from the transcript, including its store and context-projection behavior, before dispatch.",
    ],
    status: "spec",
    routing: "self",
    reviewGate: "none",
    deps: [],
    authoredBy: "David",
    createdAt: SEED_TIMESTAMP,
    updatedAt: SEED_TIMESTAMP,
  },
  {
    id: "S3.3",
    epicId: "track-3",
    epicTitle: "Agent memory & workspace",
    title: "Agent REPL (persistent)",
    intent:
      "Define a persistent interactive execution surface with an appropriate sandbox boundary.",
    acceptanceCriteria: [
      "Specify the persistent REPL and evaluate reusing Eve's per-session microsandbox versus a dedicated sandbox before dispatch.",
    ],
    status: "spec",
    routing: "self",
    reviewGate: "none",
    deps: [],
    authoredBy: "David",
    createdAt: SEED_TIMESTAMP,
    updatedAt: SEED_TIMESTAMP,
  },
  {
    id: "S5.1",
    epicId: "track-5",
    epicTitle: "Hygiene",
    title: "Emphasis extraction",
    intent:
      "Extract imperative emphasis into a reusable headless UI primitive and rewire the agent highlight path to consume it so the capability does not orphan.",
    acceptanceCriteria: [
      "Extract agent-dom-effects into @workspace/ui imperative-emphasis, rewire the sigil-chat agent path, and verify the live agent-highlight path in the browser.",
    ],
    status: "ready",
    routing: "claude:sonnet",
    reviewGate: "browser:David",
    deps: [],
    authoredBy: "David",
    createdAt: SEED_TIMESTAMP,
    updatedAt: SEED_TIMESTAMP,
  },
  {
    id: "S5.2",
    epicId: "track-5",
    epicTitle: "Hygiene",
    title: "Fix stale @niwork docs",
    intent:
      "Correct the stale Sigil Chat documentation so it names the current @zigil packages and the graduated development history.",
    acceptanceCriteria: [
      "Update sigil-chat-dev/CLAUDE.md to replace stale @niwork/agent* names and correct the graduated @niwork paragraph without changing unrelated guidance.",
    ],
    status: "ready",
    routing: "pi:luna",
    reviewGate: "peer",
    deps: [],
    authoredBy: "David",
    createdAt: SEED_TIMESTAMP,
    updatedAt: SEED_TIMESTAMP,
  },
];

export function createWorkItemsDocument(): WorkItemsDocument {
  return {
    revision: 0,
    stories: structuredClone(seedStories),
    comments: [],
    reviews: [],
    history: [],
  };
}
