import { execFileSync } from "node:child_process"
import fs from "node:fs/promises"

const COMPONENT_META_GENERATED_AT_RE =
  /export const COMPONENT_META_GENERATED_AT = ("(?:\\.|[^"\\])*")/
const COMPONENT_META_ENTRY_RE = /^\s*"([^"]+)": \{ addedAt: "([^"]+)" \},$/gm
const ISO_DATE_RE = /^\d{4}-\d{2}-\d{2}T/

export async function readPreviousComponentMeta(filePath) {
  try {
    return parseComponentMeta(await fs.readFile(filePath, "utf8"))
  } catch (error) {
    if (error && error.code === "ENOENT") {
      return { generatedAt: null, addedAtByName: new Map() }
    }
    throw error
  }
}

export function parseComponentMeta(source) {
  const generatedAtMatch = source.match(COMPONENT_META_GENERATED_AT_RE)
  const generatedAt = generatedAtMatch ? JSON.parse(generatedAtMatch[1]) : null
  const addedAtByName = new Map()

  for (const match of source.matchAll(COMPONENT_META_ENTRY_RE)) {
    addedAtByName.set(match[1], match[2])
  }

  return {
    generatedAt: isValidIsoDate(generatedAt) ? generatedAt : null,
    addedAtByName,
  }
}

export function resolveComponentMetaGeneratedAt(entries, previousMeta, now = new Date()) {
  const previousGeneratedAt = isValidIsoDate(previousMeta.generatedAt) ? previousMeta.generatedAt : null
  const hasNewUntrackedEntry = entries.some(
    (entry) => !entry.gitAddedAt && !previousMeta.addedAtByName.has(entry.name),
  )

  if (hasNewUntrackedEntry) {
    return now.toISOString()
  }

  const latestGitDate = entries
    .map((entry) => entry.gitAddedAt)
    .filter(isValidIsoDate)
    .reduce(
      (latest, candidate) =>
        !latest || Date.parse(candidate) > Date.parse(latest) ? candidate : latest,
      null,
    )

  if (previousGeneratedAt) {
    // A component may be committed after metadata was first generated. Keep
    // repeat builds stable, but never leave the reference clock behind an
    // item's addedAt timestamp or isNew() would reject it as "from the future".
    return latestGitDate && Date.parse(latestGitDate) > Date.parse(previousGeneratedAt)
      ? latestGitDate
      : previousGeneratedAt
  }

  return latestGitDate ?? "1970-01-01T00:00:00.000Z"
}

export function buildComponentMetaModule(
  registry,
  { generatedAt, previousMeta, packageRoot, newWindowHours = 72 },
) {
  const entries = []

  for (const item of registry.items) {
    const sourcePath = sourcePathForRegistryItem(item)
    if (!sourcePath) continue

    const gitAddedAt = gitAddedAtForPath(packageRoot, sourcePath)
    entries.push({
      name: item.name,
      addedAt: gitAddedAt ?? previousMeta.addedAtByName.get(item.name) ?? generatedAt,
    })
  }

  entries.sort((a, b) => a.name.localeCompare(b.name))

  const lines = [
    "// AUTO-GENERATED by scripts/build-registry.mjs — do not edit by hand.",
    "export interface ComponentMeta { addedAt: string }",
    `export const COMPONENT_META_GENERATED_AT = ${JSON.stringify(generatedAt)}`,
    "export const COMPONENT_META: Record<string, ComponentMeta> = {",
  ]

  for (const { name, addedAt } of entries) {
    lines.push(`  ${JSON.stringify(name)}: { addedAt: ${JSON.stringify(addedAt)} },`)
  }

  lines.push(
    "}",
    `const NEW_WINDOW_HOURS = ${newWindowHours}`,
    `/** True if the component was first added within NEW_WINDOW_HOURS (${newWindowHours}h) of the build (generatedAt). SSR-safe: compares only baked timestamps, never Date.now(). */`,
    "export function isNew(name: string, referenceIso: string = COMPONENT_META_GENERATED_AT): boolean {",
    "  const meta = COMPONENT_META[name]",
    "  if (!meta) return false",
    "",
    "  const addedAtMs = Date.parse(meta.addedAt)",
    "  const referenceMs = Date.parse(referenceIso)",
    "  if (!Number.isFinite(addedAtMs) || !Number.isFinite(referenceMs)) return false",
    "",
    "  const ageMs = referenceMs - addedAtMs",
    "  return ageMs >= 0 && ageMs <= NEW_WINDOW_HOURS * 60 * 60 * 1000",
    "}",
    "",
  )

  return lines.join("\n")
}

export function sourcePathForRegistryItem(item) {
  const firstPath = item.files?.[0]?.path
  if (typeof firstPath !== "string") return null

  const sourcePath = firstPath.startsWith(".registry-staging/")
    ? firstPath.slice(".registry-staging/".length)
    : firstPath
  return sourcePath.startsWith("src/") ? sourcePath : null
}

export function gitAddedAtForPath(packageRoot, relPath) {
  let output = ""

  try {
    output = execFileSync(
      "git",
      [
        "-C",
        packageRoot,
        "log",
        "--diff-filter=A",
        "--follow",
        "--format=%aI",
        "--no-patch",
        "--diff-merges=first-parent",
        "--",
        relPath,
      ],
      { encoding: "utf8", stdio: ["ignore", "pipe", "ignore"] },
    )
  } catch {
    return null
  }

  const dates = output
    .split(/\r?\n/)
    .map((line) => line.trim())
    .filter((line) => ISO_DATE_RE.test(line))

  return dates.at(-1) ?? null
}

function isValidIsoDate(value) {
  return typeof value === "string" && ISO_DATE_RE.test(value) && Number.isFinite(Date.parse(value))
}
