export const overlayPaths = Object.freeze([
  ".env.example",
  ".agents/skills",
  ".claude/skills",
  ".pi/skills",
  "docs/guides",
  "package.json",
  "pnpm-workspace.yaml",
  "sigil.doctor.json",
  "turbo.json",
  "fixtures",
  "scripts",
  "apps/agent",
  "apps/web",
  "packages/agent-contracts",
  "packages/agent-tools",
  "packages/artifact-store",
  "packages/blackboard-store",
  "packages/chat",
  "packages/data",
  "packages/graph",
  "packages/graph-store",
  "packages/review",
  "packages/review-store",
  "packages/runtime-env",
  "packages/work-items-store",
  "packages/ui/package.json",
  "packages/ui/tsconfig.json",
  "packages/ui/src/components/agent-variants.tsx",
  "packages/ui/src/components/agent-hud.tsx",
  "packages/ui/src/components/ambient-panel.tsx",
  "packages/ui/src/components/annotation-overlay.tsx",
  "packages/ui/src/components/blocks/kanban-board.tsx",
  "packages/ui/src/components/dnd/sortable.tsx",
  "packages/ui/src/components/effects/imperative-emphasis.tsx",
  "packages/ui/src/components/floating-dock.tsx",
  "packages/ui/src/components/layouts/shells.tsx",
  "packages/ui/src/components/part-projection.tsx",
  "packages/ui/src/components/quest-log.tsx",
  "packages/ui/src/components/tool-call.tsx",
  "packages/ui/src/components/tool-renderer-registry.tsx",
  "packages/ui/src/components/tone-chip.tsx",
  "packages/ui/src/components/views/entity-browser.tsx",
  "packages/ui/src/hooks/use-attachments.ts",
  "packages/ui/src/hooks/use-clipboard.ts",
  "packages/ui/src/hooks/use-file-upload.ts",
  "packages/ui/src/lib/agent-hud-state.ts",
  "packages/ui/src/lib/image-url.ts",
  "packages/ui/src/lib/imperative-emphasis.ts",
])

export const coverageRoots = Object.freeze({
  productRoutes: "apps/web/src/routes",
  productWorkspace: "apps/web/src",
  rootLaunchers: "scripts",
  fixtures: "fixtures",
})

export const requiredWorkspacePackages = Object.freeze([
  "packages/agent-contracts",
  "packages/agent-tools",
  "packages/artifact-store",
  "packages/blackboard-store",
  "packages/chat",
  "packages/data",
  "packages/graph",
  "packages/graph-store",
  "packages/review",
  "packages/review-store",
  "packages/runtime-env",
  "packages/work-items-store",
])

export const consumerTransformedPaths = Object.freeze([
  "package.json",
  "pnpm-workspace.yaml",
])
